services:
  - type: web
    name: frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: npx serve -s frontend/dist -l 3000
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        scope: shared
      - key: JWT_SECRET_KEY
        scope: shared
      - key: GOOGLE_GENAI_APIKEY
        scope: shared